# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'DidIt' do
  pod 'Digits'
  pod 'SimulatorRemoteNotifications', '~> 0.0.3'
  pod 'le'
  pod 'Alamofire'
end

target 'DidItTests' do

end
